---
# tasks file for sample-apache
- name: Install httpd, mod_ssl and php packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - mod_ssl
    - php
    - firewalld
- name: Ensure Apache and firewalld is running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - httpd
    - firewalld
- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "80/tcp"
    - "443/tcp"
- name: copy index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart apache

